### ISSUE TITLE
sql

### ISSUE THREAD

**Issue by nagexiaochengzi** [EagleBlood/MovieGOAdmin#1]
请问sql文件在哪

**Comment by EagleBlood** [comment]
Sorry for late reply, you can find SpringBoot API in here: [**MovieGOApi**](https://github.com/EagleBlood/MovieGOApi). 

Later on it will have finished README for now you can use:
1. master branch: for android app use
2. movieGoNative-bookApi: for react

You still need to create your own DB, raw sql files will be avaiable soon.

**Comment by EagleBlood** [comment]
@nagexiaochengzi 
Here is the sql file you were looking for: [file](https://github.com/EagleBlood/MovieGOApi/blob/main-android/cinema.sql)
